### ISSUE TITLE
关于喵崽和nonebot的关联复合使用

### ISSUE THREAD

**Issue by wu5288540** [yoimiya-kokomi/Miao-Yunzai#163]
由于喵崽现在使用了icqq的6号协议，而nonebot也需要go-cqhttp的6号协议启动，因此二者只能有一个登录，另一个必被踢
go-cqhttp的设置上的不同是加了一个ws-reverse，设定为universal: ws://127.0.0.1:8080/onebot/v11/ws，从而与采用了onebot协议的nonebot关联
不知道技术上两者有没有办法使用同一个icqq，用喵崽内置icqq替代go-cqhttp是否可行？与其他采用了icqq协议的bot是否也有兼容的可能？

目前的并存解决方案只能是喵崽用安卓手表扫码，go-cqhttp用6号协议，其余全部报错，除非开新的小号

技术水平低不知道怎么搞，求各位大佬指点

**Comment by Xcating** [comment]
使用ws插件

**Comment by Xcating** [comment]
https://gitee.com/xiaoye12123/ws-plugin
