### ISSUE TITLE
掉线通知提醒过于频繁

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/Miao-Yunzai#194]
当前通知大约10秒一次，但是在如果处于此状态下，
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/53306377/62d361bb-0b6a-45a5-b023-c08cd863dbda)
且无法及时重启时，会造成大量通知，是否可以调整通知间隔时间或者自定义通知间隔时间。

**Comment by Tsuk1ko** [comment]
+1，而且掉线之后很长时间都重连不上，基本都得手动 restart
