### ISSUE TITLE
功能方面

### ISSUE THREAD

**Issue by wrl2000** [yoimiya-kokomi/Miao-Yunzai#197]
目前无法通过#+武器名称/圣遗物套装名称，查看具体的介绍，希望作者后续能够加入进去。
我记得之前的yunbot是可以通过例如#雾切,查看雾切武器的详细介绍的，或者#风套，查看风套的具体介绍

**Comment by B1ackSand** [comment]
建议使用 [xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)

**Comment by wrl2000** [comment]
> 建议使用 [xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)

安装之后还是无法查看圣遗物图鉴和武器图鉴内容

**Comment by YuuLong** [comment]
> > 建议使用 [xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)
> 
> 安装之后还是无法查看圣遗物图鉴和武器图鉴内容

请按照插件说明，首次安装先执行#图鉴更新，再#重启，
#图鉴设置 内可以更改设置

**Comment by YuuLong** [comment]
> > 建议使用 [xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)
> 
> 安装之后还是无法查看圣遗物图鉴和武器图鉴内容

请按照插件说明，首次安装先执行#图鉴更新，再#重启，
#图鉴设置 内可以更改设置

**Comment by 244030119** [comment]
用这个新图鉴吧，xiaoyao的三天两头出问题不是很好用
Nwflower/Atlas 
https://github.com/Nwflower/atlas

**Comment by wrl2000** [comment]
> 用这个新图鉴吧，xiaoyao的三天两头出问题不是很好用 Nwflower/Atlas https://github.com/Nwflower/atlas

这个方案可行

**Comment by wrl2000** [comment]
https://github.com/Nwflower/atlas 这个插件可以
