### ISSUE TITLE
启动的时候报错

### ISSUE THREAD

**Issue by HUST-996** [yoimiya-kokomi/Miao-Yunzai#201]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/82724516/6825e60d-2964-4198-a1d0-13ff0873a06f)
如图，克隆的最新的版本，但是报错。
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/82724516/c0c2d28a-a2af-4237-8fd4-fee98f8d0e35)
node的版本是16

**Comment by MuXia-0326** [comment]
配置签名服务器 或者 使用手表协议登录
