### ISSUE TITLE
账号冻结 不知道是升级了icqq的问题还是tx最近风控

### ISSUE THREAD

**Issue by sakurasep** [yoimiya-kokomi/Miao-Yunzai#205]
三个号 每个号都坚持不了一天，是直接冻结，需要人脸解冻
自己搭建api以及用别人的api脚本都不行 只能说看看后续有没有别的办法

**Comment by wuhen007** [comment]
最新的icqq4.11 是8.9.68协议，需要sgin也是对应的版本。
新协议大概率会冻结一次，是正常情况，解冻后基本稳定。

**Comment by sakurasep** [comment]
> 最新的icqq4.11 是8.9.68协议，需要sgin也是对应的版本。
> 新协议大概率会冻结一次，是正常情况，解冻后基本稳定。
> 

已经基本解决 之前是4.10 现在升级到4.11已经稳定了
