### ISSUE TITLE
签名API（energy）异常

### ISSUE THREAD

**Issue by AmazingFlame** [yoimiya-kokomi/Miao-Yunzai#206]
我的机器人在日本的亚马逊云上，从昨天开始就出现这个报错：
'''
[MiaoYz][11:29:39.149][ERRO] [qsign]签名api(energy)异常： 810_9 result: {"code":-1,"msg":"timeout of 20000ms exceeded"}
[MiaoYz][11:29:59.167][ERRO] [qsign]签名api异常： wtlogin.login result: {"code":-1,"msg":"timeout of 20000ms 
'''
导致登录还在，但是发不了图片。今天重启后，登录都不行了。

**Comment by touchscale** [comment]
注：如需支持新版qsign，请在请在签名地址后添加key参数，例如：sign_api_addr: http://127.0.0.1:8080/sign?key=123456

**Comment by touchscale** [comment]
> 注：如需支持新版qsign，请在请在签名地址后添加key参数，例如：sign_api_addr: http://127.0.0.1:8080/sign?key=123456

请确认一下你的签名APi的版本

**Comment by AmazingFlame** [comment]
谢谢，我研究下，我也看到大佬在隔壁网站的回复了。我没有自己部署签名API，这是miao-yunzai自带的么？

**Comment by touchscale** [comment]
> 谢谢，我研究下，我也看到大佬在隔壁网站的回复了。我没有自己部署签名API，这是miao-yunzai自带的么？ 
> 

签名APi需要自行部署或者找部署好并且公开的

**Comment by AmazingFlame** [comment]
我看到miaoyunzai里用的[甘城猫猫] / [MAO脚本]的签名服务器？ key要什么？ 要去找作者本人问么

**Comment by touchscale** [comment]
> 我看到miaoyunzai里用的[甘城猫猫] / [MAO脚本]的签名服务器？ key要什么？ 要去找作者本人问么

如果你用的是他人搭建好的签名APi，那就需要找本人索要，如果是自己搭建，就可以在配置文件进行配置

**Comment by AmazingFlame** [comment]
好的， 谢谢了。我已经找到原作者，他今天关机维护了。没事了。

**Comment by AmazingFlame** [comment]
解决了，复制的huggingface别人的空间。https://github.com/CikeyQi/QQsign_docs/blob/main/index.md
