### ISSUE TITLE
更新抽卡记录的时候 能否把星铁的记录一起更新

### ISSUE THREAD

**Issue by meng-fucius** [yoimiya-kokomi/Miao-Yunzai#208]
原神的抽卡记录 在绑定了stoken的情况下 使用#更新抽卡记录 这个命令就能直接更新记录 非常方便 但是现在星铁的记录只能通过发送抽卡链接的方式获取 星铁的记录在绑了stoken的情况下能否一起更新呢 或者是用 #更新星铁抽卡记录 这样的命令

**Comment by hutao571** [comment]
https://github.com/ctrlcvs/xiaoyao-cvs-plugin/issues/91
