### ISSUE TITLE
如何迁移

### ISSUE THREAD

**Issue by AllureLove98** [yoimiya-kokomi/Miao-Yunzai#23]
我可以从Yunzai迁移到Miao-Yunzai吗？ 如果可以的话我迁移时应该保留那些文件才不会丢失用户数据

**Comment by luodeb** [comment]
把yunzai目录下面的config，data，genshin_config三个文件夹复制过来，然后plugins文件夹里面你需要的插件复制过来就可以了

**Comment by AllureLove98** [comment]
OK 感谢你
