### ISSUE TITLE
如何在群聊内关闭机器人

### ISSUE THREAD

**Issue by vic233333** [yoimiya-kokomi/Miao-Yunzai#234]
请问机器人能否被群聊的管理员或者群主控制开启或者关闭，而不是我自己来独立控制机器人在群聊内的开关，应该如何操作？目前管理员想要关机器人似乎只能通过禁言的方式，但是那样会容易触发风控。

**Comment by lin-junliang** [comment]
[小雪](https://gitee.com/XueWerY/XiaoXuePlugin)

**Comment by vic233333** [comment]
感谢
