### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by canyi2** [yoimiya-kokomi/Miao-Yunzai#27]
装py-plugin插件，然后装依赖，，会把puppeteer Chromium掉了，，导致puppeteer Chromium 启动失败。
![@6~V9U86PN~5))VDBLQPMCU](https://user-images.githubusercontent.com/95406510/225531739-ea2917eb-19c4-4a9c-87a3-e7fa38724c41.png)
![image](https://user-images.githubusercontent.com/95406510/225531844-99b54eab-6530-4c7c-b767-7afbb2656149.png)
具体情况就是上述图片展示

**Comment by canyi2** [comment]
我自己的，已解决，解决方案就是重装chromium，相关指令：/node node modules/puppeteer/install.js

**Comment by Fhm-newbie** [comment]
能问一下chromium咋重装的吗？我换服务器的时候也碰见这个问题了。。。

**Comment by canyi2** [comment]
看上一条，云崽目录敲指令

**Comment by Fhm-newbie** [comment]
我这边还是不行。。。我自己重新配置看看吧。。。

**Comment by canyi2** [comment]
要么就是重新安装依赖

**Comment by Fhm-newbie** [comment]
我尝试了：
1、删除node_module重新pnpm install -P
2、删除root/.cache/puppeteer再运行node node_modules/puppeteer/install.js
3、apt remove再apt install
都不太行
现在已经在准备直接服务器重装系统了
