### ISSUE TITLE
星铁抽卡记录更新出问题了

### ISSUE THREAD

**Issue by liuzj288** [yoimiya-kokomi/Miao-Yunzai#278]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/13833404/5b2368c5-7aae-406e-98a9-7c086869e717)
[MiaoYz][08:44:26.524][ERRO] [抽卡记录][getLog]
[MiaoYz][08:44:26.525][ERRO] TemplateError: anonymous:56:32
    54|                onerror="whenError(this,'{{val.item_type=='角色'?'role':'weapon'}}')"/>
    55|           
 >> 56|           <div class="num_name {{val.num<=10?'gold': (val.num<log.max*0.5 ? 'good' : (val.num<log.max*0.83) ? 'normal': 'bad')}}" >{{val.num}}</div>
    57|         </div>
    58|         {{/each}}
    59|       </div>

RuntimeError: Cannot read properties of undefined (reading 'max')

**Comment by touchscale** [comment]
#277

**Comment by touchscale** [comment]
可以照着这个PR先自己改一下
