### ISSUE TITLE
配置了签名服务器突然无法登录（版本过低）

### ISSUE THREAD

**Issue by MUKAPP** [yoimiya-kokomi/Miao-Yunzai#280]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/41848070/280782b7-23c2-4224-82aa-44236f115805)
如图，之前就配置了签名服务器，前些天还没有问题，那会突然掉线，再次登录就不行了
又试了8968，8973，都不行

**Comment by MUKAPP** [comment]
发现 新账号+8973 可以正常登录

**Comment by yelinlan** [comment]
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/38036830/4521e621-908c-4667-a59f-a2b5447348a8)

**Comment by xueqi5201314** [comment]
> 新号也不行了呜呜

现在有人已经发不了8.9.76及以上的了

**Comment by misaka20002** [comment]
更新icqq，用8973，换macOS

**Comment by ZM-J** [comment]
> 更新icqq，用8973，换macOS

实测icqq 0.5.3 + 8973 + macOS 仍然不行

~而且macOS所用到的协议名称貌似是iMac_6.8.2.21241吧？~

**Comment by touchscale** [comment]
https://github.com/touchscale/Qsign

去我仓库下载75.76.78.80的文件试试，不推荐用80，除非75.76.78登录不上

**Comment by Midnight-2004** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2471
原因见上
现在是能用一天是一天了

**Comment by Inky-Moon** [comment]
8980可以

**Comment by touchscale** [comment]
> https://github.com/touchscale/Qsign
> 
> 去我仓库下载75.76.78.80的文件试试，不推荐用80，除非75.76.78登录不上

目前我仓库已更新83.85版本的文件，可以尝试

**Comment by oneXiaoYou** [comment]
windows下可以尝试一键qsign方案，目前稳定使用中
https://gitee.com/Code_XiaoYou/windows-one-click-qsign
