### ISSUE TITLE
#全部更新 之后 监听事件错误

### ISSUE THREAD

**Issue by MUKAPP** [yoimiya-kokomi/Miao-Yunzai#286]
![Screenshot_20231016111745](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/41848070/36c804e2-4035-4053-922b-9259f7479a16)
如图，正常登录，无法处理消息

**Comment by MUKAPP** [comment]
已解决。

**Comment by XJLZ** [comment]
怎么解决的啊，我也遇到了

**Comment by MUKAPP** [comment]
> 怎么解决的啊，我也遇到了

就用git强制跟远程同步一下（）
