### ISSUE TITLE
Lain-plugin是什么？

### ISSUE THREAD

**Issue by TheTychoStar** [yoimiya-kokomi/Miao-Yunzai#312]
绑定用户功能更新里写到：“如需链接至其他平台需使用TRSS-Yunzai或Lain-plugin”。
我搜了半天没搜到这个lain-plugin，有没有好心人请给指个路，谢谢。

**Comment by Zyy955** [comment]
https://github.com/Zyy955/Lain-plugin

**Comment by TheTychoStar** [comment]
> https://github.com/Zyy955/Lain-plugin

感恩！谢谢！
