### ISSUE TITLE
xiaoyao-cvs-plugins 在docker中运行出错ERR_PNPM_INCLUDED_DEPS_CONFLICT 解决办法

### ISSUE THREAD

**Issue by tignioj** [yoimiya-kokomi/Miao-Yunzai#333]
安装逍遥插件，并在docker-compose中开启了路径映射
```
    volumes:
      - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/Miao-Yunzai/plugins/xiaoyao-cvs-plugin    # 图鉴插件
```
运行时报错
```
miao-yunzai  |  ERR_PNPM_INCLUDED_DEPS_CONFLICT  modules directory (at "/app/Miao-Yunzai") was installed with optionalDependencies, dependencies. Current install wants optionalDependencies, dependencies, devDependencies.
```
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/38057269/4d77c3de-f0aa-402e-a2ae-1da5f596008e)

通过查找关键词ERR_PNPM_INCLUDED_DEPS_CONFLICT ，找到了曾经的解决方案 https://gitee.com/yoimiya-kokomi/Yunzai-Bot/issues/I6UYG7
，于是修改`docker/docker-entrypoint.sh`
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/38057269/742f930d-6bcb-4b99-90b6-866befcebe1e)

添加了这几行
```shell
        echo "解决ERR_PNPM_INCLUDED_DEPS_CONFLICT依赖冲突错误"
        cd $WORK_DIR
        pnpm install <<EOF
        y
EOF
        cd $XIAOYAO_CVS_PATH
```
然后重新构建并运行`docker compose build && docker compose up`，日志无报错
![image](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/38057269/03d32dc5-43c6-4728-b808-4b9e13753260)

我对pnpm没有过多的了解，但是这样确实解决了问题。

**Comment by 1294266616** [comment]
貌似降级pnpm到7.30也行，之前历史记录里有后面给移除了
