### ISSUE TITLE
监听事件错误

### ISSUE THREAD

**Issue by akua0z** [yoimiya-kokomi/Miao-Yunzai#355]
![Screenshot_2024-01-20-16-21-51-463_com.kodcloud.kodbox-edit.jpg](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/113225788/f5de2d89-4815-4148-b7c8-6b0798a6a76d)

运行报错，看起来是sqlite3问题，尝试过重新安装，但是没有啥效果，求解决办法

**Comment by iedhgherljhfloj** [comment]
pnpm install sqlite3@5.1.6 -w

**Comment by akua0z** [comment]
> pnpm install sqlite3@5.1.6 -w
> 

感谢大佬，成功解决问题！
