### ISSUE TITLE
设置完主人QQ后，私聊仍然显示没有主人权限

### ISSUE THREAD

**Issue by Rurilitt** [yoimiya-kokomi/Miao-Yunzai#369]
yunzai3.1.3 miao2.5.8
喵喵已经给主人QQ发消息了，但是反过来没办法发指令设置
![QQ截图20240212112509](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/159548445/4e299d4e-b56a-4ccb-9e0e-48c13263a996)

**Comment by xueqi5201314** [comment]
一般来看，要么锅巴改，要么重装

**Comment by Rurilitt** [comment]
> 一般来看，要么锅巴改，要么重装

锅巴要主人登录，由于现在不识别，锅巴也进不去。。。那看来只能后面找个时间重装了。。

**Comment by Rurilitt** [comment]
重装恢复正常
