### ISSUE TITLE
角色记录错误

### ISSUE THREAD

**Issue by ayakasuki** [yoimiya-kokomi/Miao-Yunzai#39]
![image](https://user-images.githubusercontent.com/20859971/226610764-814257a5-930d-498e-9970-58808a3bceb0.png)

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/226611089-7185d849-7ba4-41e1-821a-f3f23f35b752.png)
关闭这个 就可以了 可能是喵喵的角色分析有问题

**Comment by Dr-WeiAL** [comment]
我也遇到了这个问题

**Comment by yoimiya-kokomi** [comment]
更新最新版miao-plugin

**Comment by Dr-WeiAL** [comment]
> 更新最新版miao-plugin

好的解决了，感谢
