### ISSUE TITLE
在已有星铁跃迁记录的情况下直接唤起机器人会提示无记录

### ISSUE THREAD

**Issue by Lucas04-nhr** [yoimiya-kokomi/Miao-Yunzai#403]
已经事先导入好了跃迁记录，但是在之后查询时显示无记录。
<img width="681" alt="image" src="https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/117806313/fde27338-8e81-4cb4-82b6-4aa583878ae0">
只有输入命令为“*星铁全部记录”时才能看见记录。
<img width="672" alt="image" src="https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/117806313/edfcf879-70e4-4500-8f94-e9fb376993f3">

**Comment by 8852690** [comment]
看你的图似乎是使用了starrail-plugin, 这个插件的优先级非常高, 会拦截掉对应的指令. 而且, 由于该插件的抽卡记录与本体的抽卡记录存储位置不同, 所以你出现了这个'暂无抽卡记录'的提示.

**Comment by Lucas04-nhr** [comment]
> 看你的图似乎是使用了starrail-plugin, 这个插件的优先级非常高, 会拦截掉对应的指令. 而且, 由于该插件的抽卡记录与本体的抽卡记录存储位置不同, 所以你出现了这个'暂无抽卡记录'的提示.

感谢指引，那请问除了卸载`starrail-plugin`之外还有什么解决办法呢，找了下文档结果好像没找到……

**Comment by 8852690** [comment]
> > 看你的图似乎是使用了starrail-plugin, 这个插件的优先级非常高, 会拦截掉对应的指令. 而且, 由于该插件的抽卡记录与本体的抽卡记录存储位置不同, 所以你出现了这个'暂无抽卡记录'的提示.
> 
> 感谢指引，那请问除了卸载`starrail-plugin`之外还有什么解决办法呢，找了下文档结果好像没找到……

Emmm... 你可以尝试去星铁插件的把apps/gacha.js最后的
```
catch (err) {
      logger.error(err)
      await e.reply('本地暂无抽卡记录，请发送#星铁更新跃迁，更新抽卡记录')
    }
```
修改为:
```
catch (err) {
      logger.error(err)
      await e.reply('本地暂无抽卡记录，请发送#星铁更新跃迁，更新抽卡记录')
      return false;
    }
```
在找不到记录的时候, 尝试返回给其他插件处理(也就是调用本体的抽卡记录?)

**Comment by Lucas04-nhr** [comment]
> > > 看你的图似乎是使用了starrail-plugin, 这个插件的优先级非常高, 会拦截掉对应的指令. 而且, 由于该插件的抽卡记录与本体的抽卡记录存储位置不同, 所以你出现了这个'暂无抽卡记录'的提示.
> > 
> > 
> > 感谢指引，那请问除了卸载`starrail-plugin`之外还有什么解决办法呢，找了下文档结果好像没找到……
> 
> Emmm... 你可以尝试去星铁插件的把apps/gacha.js最后的
> 
> ```
> catch (err) {
>       logger.error(err)
>       await e.reply('本地暂无抽卡记录，请发送#星铁更新跃迁，更新抽卡记录')
>     }
> ```
> 
> 修改为:
> 
> ```
> catch (err) {
>       logger.error(err)
>       await e.reply('本地暂无抽卡记录，请发送#星铁更新跃迁，更新抽卡记录')
>       return false;
>     }
> ```
> 
> 在找不到记录的时候, 尝试返回给其他插件处理(也就是调用本体的抽卡记录?)

感谢，已经解决！
