### ISSUE TITLE
错误类型： TypeError  错误信息： 无法读取未定义的属性（读取“event”）

### ISSUE THREAD

**Issue by 244030119** [yoimiya-kokomi/Miao-Yunzai#418]
[MiaoYz][09:37:00.377][MARK] Miao-Yunzai 启动中...
[MiaoYz][09:37:00.445][INFO] 正在连接 redis://127.0.0.1:6379/0
[MiaoYz][09:37:00.519][INFO] Redis 连接成功
[MiaoYz][09:37:00.648][MARK] ----------
[MiaoYz][09:37:00.649][MARK] Package Version: icqq@0.6.10 (Released on 2024/2/4)
[MiaoYz][09:37:00.651][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[MiaoYz][09:37:00.652][MARK] ----------
[MiaoYz][09:37:03.918][INFO] 加载渲染后端 puppeteer
[MiaoYz][09:37:05.118][INFO] [3319009309]获取到签名Api协议版本：8.9.78
[MiaoYz][09:37:05.120][INFO] [3319009309]使用协议：aPad_8.9.78.12275
[MiaoYz][09:37:06.120][MARK] 157.148.55.96:8080 connected
[MiaoYz][09:37:06.207][MARK] Welcome, 宵宫大姐姐 ! 正在加载资源...
[MiaoYz][09:37:07.003][MARK] 加载了242个好友，66个群，0个频道，20个陌生人
[MiaoYz][09:37:07.010][MARK] ----^_^----
[MiaoYz][09:37:07.015][MARK] Miao-Yunzai 上线成功 版本v3.1.3
[MiaoYz][09:37:07.018][MARK] https://github.com/yoimiya-kokomi/Miao-Yunzai
[MiaoYz][09:37:07.335][INFO] -----------
[MiaoYz][09:37:07.336][INFO] 加载插件中...
[MiaoYz][09:37:08.286][INFO] ------（-＾〇＾-）-----
[MiaoYz][09:37:08.286][INFO] 清凉图插件极速加载中～
[MiaoYz][09:37:08.287][INFO] -----(/^▽^)/------
[MiaoYz][09:37:08.432][INFO] ---------QAQ---------
[MiaoYz][09:37:08.433][INFO] Atlas图鉴4.3.0很高兴为您服务~
[MiaoYz][09:37:08.814][INFO] R插件1.6.7初始化
[MiaoYz][09:37:08.954][INFO] --------(≧▽≦)/--------
[MiaoYz][09:37:08.956][INFO] 小月插件undefined初始化~
[MiaoYz][09:37:08.957][INFO] -------------------------
[MiaoYz][09:37:09.071][INFO] -----------＾ω＾----------
[MiaoYz][09:37:09.077][INFO] 插件管理器1.3.1初始化~
[MiaoYz][09:37:09.188][INFO] ----ヾ(￣▽￣)Bye~Bye~----
[MiaoYz][09:37:09.190][INFO] 椰奶插件1.4.1初始化~
[MiaoYz][09:37:09.192][INFO] -------------------------
[MiaoYz][09:37:09.554][INFO] 止水插件1.2.6 正在加载...
[MiaoYz][09:37:12.785][INFO] ---------!_!---------
[MiaoYz][09:37:12.786][INFO] 自动化插件1.0.5载入成功
[MiaoYz][09:37:13.231][INFO] -----------(∗❛ั∀❛ั∗)✧*。--------------
[MiaoYz][09:37:13.232][INFO] ~	欢迎使用枫叶插件1.7.1	~
[MiaoYz][09:37:13.233][INFO] ~	原作者->  kesally&七七(2770706493)	
[MiaoYz][09:37:13.234][INFO] ~	枫叶群  779217677	~
[MiaoYz][09:37:13.235][INFO] ~	我们的频道  https://pd.qq.com/s/13ptnp2ew	~
[MiaoYz][09:37:13.236][INFO] ~	ikun群  707499227	~
[MiaoYz][09:37:13.236][INFO] ------------------------------------
[MiaoYz][09:37:13.498][INFO] -----------
[MiaoYz][09:37:13.499][INFO] 加载碎月插件完成..[v1.0.0]
[MiaoYz][09:37:13.499][INFO] -----------
[MiaoYz][09:37:14.254][INFO] ---------=.=---------
[MiaoYz][09:37:14.255][INFO] 土块插件2.0.1载入成功~qwq
[MiaoYz][09:37:14.256][INFO] 作者-SunRyK曉K & 地球生物
[MiaoYz][09:37:14.256][INFO] ---------------------
[MiaoYz][09:37:14.439][INFO] ------------QAQ------------
[MiaoYz][09:37:14.440][INFO] liangshi伤害计算加载成功
[MiaoYz][09:37:14.441][INFO] 如有计算错误可通过以下方式反馈
[MiaoYz][09:37:14.441][INFO] 交流群反馈：807622774
[MiaoYz][09:37:14.442][INFO] ---------------------------
[MiaoYz][09:37:15.630][INFO] lin-plugin[2023-1-19]
[MiaoYz][09:37:15.959][ERRO] [Yenai-Plugin] 监听事件错误：input.js
[MiaoYz][09:37:15.961][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:16.746][INFO] ---------^_^---------
[MiaoYz][09:37:16.748][INFO] 喵喵插件2.5.10初始化~
[MiaoYz][09:37:17.012][ERRO] [Yenai-Plugin] 监听事件错误：message.js
[MiaoYz][09:37:17.013][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
load Uid Data Done...
[MiaoYz][09:37:19.313][INFO] 【枫叶插件】检测到未设置机器人名字
[MiaoYz][09:37:19.314][INFO]  请发送：枫叶设置，查看名字
[MiaoYz][09:37:19.317][INFO] 【枫叶插件】检测到未设置机器人名字
[MiaoYz][09:37:19.318][INFO]  请发送：枫叶设置，查看名字
[MiaoYz][09:37:19.320][INFO] 【枫叶插件】检测到未设置机器人名字
[MiaoYz][09:37:19.321][INFO]  请发送：枫叶设置，查看名字
[MiaoYz][09:37:19.344][INFO] ---------^_^---------
[MiaoYz][09:37:19.345][INFO] 小飞插件1.8.9：初始化~
[MiaoYz][09:37:19.346][INFO] 【代发言】模块载入成功！
[MiaoYz][09:37:19.348][INFO] 【原神星铁注册时间查询】模块载入成功！
[MiaoYz][09:37:19.348][INFO] 【天气】模块载入成功！
[MiaoYz][09:37:19.349][INFO] 【帮助】模块载入成功！
[MiaoYz][09:37:19.355][INFO] 【更新】模块载入成功！
[MiaoYz][09:37:19.356][INFO] 【机器人违规记录查询】模块载入成功！
[MiaoYz][09:37:19.358][INFO] 【点歌】模块载入成功！
[MiaoYz][09:37:19.358][INFO] 【设置】模块载入成功！
[MiaoYz][09:37:19.361][INFO] 【通行证ck转米游社ck】模块载入成功！
[MiaoYz][09:37:19.362][INFO] 小飞插件1.8.9：初始化完成！
[MiaoYz][09:37:19.367][INFO] ---------------------
[MiaoYz][09:37:19.393][INFO] 【小飞插件_网易云音乐ck】未设置网易云音乐ck！
[MiaoYz][09:37:19.396][ERRO] 【小飞插件_QQ音乐ck】ck已失效！
[MiaoYz][09:37:19.421][ERRO] [Yenai-Plugin] 监听事件错误：notice_friend.js
[MiaoYz][09:37:19.424][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:19.971][INFO] Atlas载入库文件：github原神成功！
[MiaoYz][09:37:20.014][INFO] Atlas载入库文件：github星铁成功！
[MiaoYz][09:37:20.026][INFO] Atlas载入库文件：github绝区零成功！
[MiaoYz][09:37:20.159][INFO] Atlas载入库文件：原神成功！
[MiaoYz][09:37:20.198][INFO] Atlas载入库文件：星铁成功！
[MiaoYz][09:37:20.216][INFO] Atlas载入库文件：绝区零成功！
[MiaoYz][09:37:20.296][INFO] ---------^_^---------
[MiaoYz][09:37:20.305][INFO] 图鉴插件1.2.9初始化~
[MiaoYz][09:37:20.331][ERRO] [Yenai-Plugin] 监听事件错误：notice_group.js
[MiaoYz][09:37:20.333][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:20.728][ERRO] [Yenai-Plugin] 监听事件错误：request.js
[MiaoYz][09:37:20.731][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:21.027][INFO] 止水插件 加载完成~！
[MiaoYz][09:37:21.504][INFO] '-------------QwQ--------------
[MiaoYz][09:37:21.507][INFO] ----FanSky_Qs插件【1.5.9】初始化中------
[MiaoYz][09:37:22.220][INFO] ********************[hanhan]********************
[MiaoYz][09:37:22.222][INFO] hanhan-plugin加载成功
[MiaoYz][09:37:22.223][INFO]             ▃▆█▇▄▖
[MiaoYz][09:37:22.224][INFO] 　 　 　 ▟◤▖      ◥█▎
[MiaoYz][09:37:22.224][INFO]    　 ◢◤　 ▐　　　  ▐▉
[MiaoYz][09:37:22.225][INFO] 　 ▗◤　　　▂　▗▖　　▕█▎
[MiaoYz][09:37:22.225][INFO] 　◤　▗▅▖◥▄　▀◣　　█▊
[MiaoYz][09:37:22.226][INFO] ▐　▕▎◥▖◣◤　　　　◢██
[MiaoYz][09:37:22.226][INFO] █◣　◥▅█▀　　　　▐██◤
[MiaoYz][09:37:22.227][INFO] ▐█▙▂　　     　◢██◤
[MiaoYz][09:37:22.227][INFO] ◥██◣　　　　◢▄◤
[MiaoYz][09:37:22.228][INFO]  　　▀██▅▇▀
[MiaoYz][09:37:22.228][INFO] 当前版本 v1.3.0
[MiaoYz][09:37:22.229][INFO] 仓库地址 https://github.com/hanhan258/hanhan-plugin
[MiaoYz][09:37:22.229][INFO] ********************[///^///]********************
[MiaoYz][09:37:22.377][ERRO] 载入插件错误：admin
[MiaoYz][09:37:22.398][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.401][ERRO] 载入插件错误：assistant
[MiaoYz][09:37:22.402][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.407][ERRO] 载入插件错误：bika
[MiaoYz][09:37:22.408][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.412][ERRO] 载入插件错误：fun
[MiaoYz][09:37:22.413][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.416][ERRO] 载入插件错误：handle
[MiaoYz][09:37:22.417][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.420][ERRO] 载入插件错误：help
[MiaoYz][09:37:22.422][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.424][ERRO] 载入插件错误：picSearch
[MiaoYz][09:37:22.426][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.428][ERRO] 载入插件错误：pixiv
[MiaoYz][09:37:22.429][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.433][ERRO] 载入插件错误：search
[MiaoYz][09:37:22.434][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.436][ERRO] 载入插件错误：setu
[MiaoYz][09:37:22.440][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.442][ERRO] 载入插件错误：state
[MiaoYz][09:37:22.444][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.445][ERRO] 载入插件错误：update
[MiaoYz][09:37:22.446][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.448][ERRO] 载入插件错误：version
[MiaoYz][09:37:22.448][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.450][ERRO] 载入插件错误：groupAdmin/groupAdmin
[MiaoYz][09:37:22.451][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.452][ERRO] 载入插件错误：groupAdmin/groupBannedWords
[MiaoYz][09:37:22.453][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.455][ERRO] 载入插件错误：groupAdmin/groupVerify
[MiaoYz][09:37:22.456][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.457][ERRO] 载入插件错误：groupAdmin/privateGroupAdmin
[MiaoYz][09:37:22.458][ERRO] SyntaxError: Unexpected token '<<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
[MiaoYz][09:37:22.896][INFO] [FanSky_Qs]检测是否有新配置开关中
[MiaoYz][09:37:23.719][INFO] Template detection:已经存在class Plugin_Manager同名导出
    ../../apps/user/Plugin_Manager.js
[MiaoYz][09:37:23.990][INFO] 配置文件检查完毕,欢迎使用，祝您使用愉快喵qwq~
[MiaoYz][09:37:23.992][INFO] [FanSky_Qs]>>将在10s后开始请求队伍伤害所需JSON
[MiaoYz][09:37:25.454][INFO] ----FanSky_Qs插件载入完成------
[MiaoYz][09:37:25.573][INFO] ⏳⏳⏳⏳⏳⏳⏳⏳
[MiaoYz][09:37:25.575][INFO] (🔨lin-Plugin🔨):"lin插件"初始化.....
[MiaoYz][09:37:25.580][INFO] ┎┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┒
[MiaoYz][09:37:25.580][INFO] ┃  ╦        ╦══╦══╦  ╦      ╔╗  ┃
[MiaoYz][09:37:25.581][INFO] ┃  ║           ║     ║     ⫽ ║  ┃
[MiaoYz][09:37:25.581][INFO] ┃  ║           ║     ║   ⫽   ║  ┃
[MiaoYz][09:37:25.582][INFO] ┃  ║           ║     ║ ⫽     ║  ┃
[MiaoYz][09:37:25.582][INFO] ┃  ╚══════  ╩══╩══╩  ╚╝      ╩  ┃
[MiaoYz][09:37:25.583][INFO] ┖┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┚
[MiaoYz][09:37:25.583][WARN] (🔨lin-Plugin🔨):若出现README.md中未提及的问题,请联系我们!!!
[MiaoYz][09:37:25.584][INFO] (🔨lin-Plugin🔨):"初始化完成,欢迎您的使用✔!
[MiaoYz][09:37:25.584][INFO] ⌛⌛⌛⌛⌛⌛⌛⌛
[MiaoYz][09:37:26.030][MARK] --------- >_< ---------
[MiaoYz][09:37:26.031][MARK] 锅巴服务启动成功~ 耗时:2349ms
[MiaoYz][09:37:26.038][MARK] http://192.168.0.101:50831
[MiaoYz][09:37:26.039][MARK] -----------------------
[MiaoYz][09:37:26.040][MARK] [Guoba] 欢迎使用锅巴插件，当前版本：1.2.1
[MiaoYz][09:37:26.453][MARK] [liangshi]预设面板自动刷新完成
[MiaoYz][09:37:26.613][INFO] 加载定时任务[12个]
[MiaoYz][09:37:26.614][INFO] 加载插件[266个]
[MiaoYz][09:37:33.995][INFO] [FanSky_Qs]>>开始检查获取所需JSON资源
[MiaoYz][09:37:35.069][INFO] [FanSky_Qs]>>已写入CHAR_DATA、HASH_TRANS、CALC_RULES、RELIC_APPEND配置项 
[MiaoYz][09:37:36.027][INFO] recv from: [Private: 244030119(friend)] #更新
[MiaoYz][09:37:36.702][ERRO] TypeError: Cannot read properties of undefined (reading 'event')
    at PluginsLoader.deal (file:///home/wujing/%E6%A1%8C%E9%9D%A2/Miao-Yunzai/lib/plugins/loader.js:256:15)
[MiaoYz][09:37:44.053][INFO] recv from: [Private: 244030119(friend)] #全部更新
[MiaoYz][09:37:44.202][ERRO] TypeError: Cannot read properties of undefined (reading 'event')
    at PluginsLoader.deal (file:///home/wujing/%E6%A1%8C%E9%9D%A2/Miao-Yunzai/lib/plugins/loader.js:256:15)

TypeError 错误解释：

您遇到的错误信息表明，您试图访问一个未定义变量的属性“event”。这通常发生在以下几种情况下：

变量未初始化： 在尝试访问属性之前，您可能没有为变量分配值。
变量值为空： 变量可能被赋值为 null 或 undefined，在这种情况下，它没有属性可以访问。
对象类型错误： 您可能试图访问一个非对象类型的属性。例如，如果将数字或字符串赋值给变量，则无法访问其“event”属性。
针对您提供的错误信息：

错误类型： TypeError
错误信息： 无法读取未定义的属性（读取“event”）
位置： PluginsLoader.deal 文件：/home/wujing/妙云斋/lib/plugins/loader.js 第 256 行，第 15 个字符
根据错误信息分析， 问题很可能是由于在 PluginsLoader.deal 函数中尝试访问 event 属性时，该属性的所属变量没有被定义或值为 null 导致的。

**Comment by 244030119** [comment]
起因是昨天想要使用rconsole-plugin插件的解析功能，按照使用说明更新了其依赖导致

root@wujing-virtual-machine:/home/wujing/桌面/Miao-Yunzai# pnpm -v
8.9.0
root@wujing-virtual-machine:/home/wujing/桌面/Miao-Yunzai# pnpm i -P --prefix ./plugins/rconsole-plugin/
Scope: all 11 workspace projects
? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/FanSky_Qs/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/Guoba-Plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/earth-k-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/hanhan-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/liangshi-calc/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/miao-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/rconsole-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/xiaofei-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/yenai-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/zhishui-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ (node:370645) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:370645) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 8.9.0 → 9.0.6.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v9.0.6   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯
✔ The modules directory at "/home/wujing/桌面/Miao-Yunzai/plugins/zhishui-plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) · true



















Recreating /home/wujing/桌面/Miao-Yunzai/plugins/rconsole-plugin/node_modules
../..                                    | -211 ---------------------

dependencies:
+ axios 1.4.0
+ p-queue 8.0.1
+ qrcode 1.5.3
+ tunnel 0.0.6

devDependencies: skipped

../yenai-plugin prepare$ husky
│ sh: 1: husky: not found
└─ Running...
 ELIFECYCLE  Command failed.

**Comment by Yvan-W** [comment]
俺不太一样，俺是今天早上起来就发现这样了呜呜呜

**Comment by 8852690** [comment]
看起来是椰奶那边的问题

**Comment by 244030119** [comment]
> 看起来是椰奶那边的问题

嗯哈，开头的<<报错都是椰奶的插件，然后 “无法读取未定义的属性（读取“event”）”这个是梁氏的插件，重装就解决了
