### ISSUE TITLE
json文件导入记录在llonebot协议上失效

### ISSUE THREAD

**Issue by wei-la-ya** [yoimiya-kokomi/Miao-Yunzai#423]
![63f04a762e1be277ac4a15db314eb579](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/142399519/b3d4d57c-40d0-4edd-8df5-6eb82dec54ac)
![5e8920a0a07451ce28e4854c068ad1f7](https://github.com/yoimiya-kokomi/Miao-Yunzai/assets/142399519/1b9e6444-60a1-4ed7-90d5-d1cc20434879)

**Comment by 8852690** [comment]
你这是trss?

**Comment by wei-la-ya** [comment]
> 这个应该属于适配器的问题???

看日志好像是接收到了文件，但是id跟icqq不一样

**Comment by 8852690** [comment]
> > 这个应该属于适配器的问题???
> 
> 看日志好像是接收到了文件，但是id跟icqq不一样

因为崽没有识别到消息里类型为file的字段, 不会生成e.file, 而抽卡记录导入主要是依赖e.file, 没有就不会触发到. 这个应该需要trss那边做适配才对, 而不是在喵崽提
