### ISSUE TITLE
关于凌晨推送时，误上传config测试文件夹导致的部分玩家自动强制更新引发的问题

### ISSUE THREAD

**Issue by ningmengchongshui** [yoimiya-kokomi/Miao-Yunzai#463]
很抱歉昨晚的疏忽，没注意.git未配置全局控制文件导致测试文件误上传。
为避免造谣或引起多方猜测，特此声明望周知。
部分使用了凌晨自动更新的用户受到了影响，今早已回退分支。
———
还有没有后门哈。也勿造谣哈。源码都是公开的。
———
顺带提醒勿开启自动更新，总会有意外的时候。来了就比较尴尬了。这不就来了。
一直主张更新重启等重要操作需手动进行。

**Comment by devil233-ui** [comment]
~~一脸懵逼点进来的人会知道自动更新在哪关么~~
