### ISSUE TITLE
zzz 的 server tag 前两个完全雷同，不知是否是故意这么写的。

### ISSUE THREAD

**Issue by ShikiSuen** [yoimiya-kokomi/Miao-Yunzai#468]
就来问一下。

![d10fa552d75aac6273a9189de0ecd987](https://github.com/user-attachments/assets/6d6bb28a-14c7-473b-ab58-f5310ea09a7b)

**Comment by rainbowwarmth** [comment]
是为了匹配服务器顺序，因为原神和星铁的官服和b服是两个不同服务器，而绝区零是只有官服，只能写两个来对齐原神和星铁的官服和b服

**Comment by ShikiSuen** [comment]
对欸，这样确实省事。
不妨留个上下文备注，省得今后再有人提出相同的疑问。
