### ISSUE TITLE
Windows Server中miao崽启动Chromium后会留下一个窗口且关闭不了

### ISSUE THREAD

**Issue by bbfhbnlvnl6** [yoimiya-kokomi/Miao-Yunzai#476]
[MiaoYz][15:12:18.784][INFO] [Yenai-Plugin][状态]背景图片请求成功 231.59KB 2669ms
[MiaoYz][15:12:18.785][DEBU] Promise Style: 2673 ms
[MiaoYz][15:12:18.993][DEBU] Promise CPU: 2885 ms
[MiaoYz][15:12:18.993][DEBU] Promise visualData: 2881 ms
[MiaoYz][15:12:18.994][DEBU] Promise all: 2882 ms
[MiaoYz][15:12:18.996][DEBU] Error: ENOENT: no such file or directory, scandir 'D:\qqbot\yunzai bot\hutai\Miao-Yunzai\plugins\example'
    at Object.readdirSync (node:fs:1507:26)
    at getPluginNum (file:///D:/qqbot/yunzai%20bot/hutai/Miao-Yunzai/plugins/yenai-plugin/model/State/OtherInfo.js:54:13)
    at otherInfo (file:///D:/qqbot/yunzai%20bot/hutai/Miao-Yunzai/plugins/yenai-plugin/model/State/OtherInfo.js:25:11)
    at getData (file:///D:/qqbot/yunzai%20bot/hutai/Miao-Yunzai/plugins/yenai-plugin/model/State/index.js:90:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NewState.state (file:///D:/qqbot/yunzai%20bot/hutai/Miao-Yunzai/plugins/yenai-plugin/apps/state.js:49:18)
    at async PluginsLoader.deal (file:///D:/qqbot/yunzai%20bot/hutai/Miao-Yunzai/lib/plugins/loader.js:275:41) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\qqbot\\yunzai bot\\hutai\\Miao-Yunzai\\plugins\\example'
}
[MiaoYz][15:12:19.033][INFO] puppeteer Chromium 启动中...
[MiaoYz][15:12:19.117][DEBU] recv:OnlinePush.ReqPush seq:-390237031
[MiaoYz][15:12:19.124][DEBU] send:OnlinePush.RespPush seq:98
[MiaoYz][15:12:19.801][INFO] puppeteer Chromium 启动成功 ws://127.0.0.1:63935/devtools/browser/3600d790-c38f-4a90-bdc8-9c9d9031b52e
[MiaoYz][15:12:19.886][DEBU] [图片生成][使用模板] ./temp/html/yenai-plugin/state/index/index.html
[MiaoYz][15:12:21.521][DEBU] recv:OnlinePush.PbPushGroupMsg seq:-1305638998
[MiaoYz][15:12:21.523][DEBU] send:group_member_card.get_group_member_card_info seq:99
然后在桌面就会多一个窗口
![110bdda882082936d114c99452bd3f7a](https://github.com/user-attachments/assets/570a427c-dc5e-47cc-9c57-9eaf97e07038)
如果在任务管理器中把edge结束后这个窗口就消失但控制台报[MiaoYz][15:12:42.443][INFO] puppeteer Chromium 强制关闭重启...
[MiaoYz][15:12:42.445][INFO] puppeteer Chromium 启动中...
[MiaoYz][15:12:43.086][DEBU] recv:OnlinePush.PbPushGroupMsg seq:-1451462288
![110bdda882082936d114c99452bd3f7a]
![cd7054e4efa7b6bbed44a64c61190f70](https://github.com/user-attachments/assets/07dda596-96ae-4104-b0e6-ac0ba7ea6ee0)
然后这个窗口又会重新出现。大佬们有什么办法解决吗？谢谢！

**Comment by bbfhbnlvnl6** [comment]
谢谢佬

**Comment by liucheng12156** [comment]
> 如果系统中有 chrome 或者 edge 会默认使用这两个来渲染截图，并且跳过 puppeteer 下载 chromium，但是 puppeteer 与 chrome 和 edge 目前最新的 129 版本不匹配 解决方法： ①回退到 128 版本； ②或者删除根目录下的 [.puppeteerrc.cjs]，删除 node_modules，重新 pnpm i 安装依赖，改用 puppeteer 默认下载的 chromium

   试过了，edge是127版本，.puppeteerrc.cjs也删了，还是会出现这个bug
