### ISSUE TITLE
希望加入#添加/删除+固定回复或者表情包功能

### ISSUE THREAD

**Issue by Oishiimono** [yoimiya-kokomi/Miao-Yunzai#60]
如题，试了下裸喵崽还不能响应这个功能，如果可以的话，是否可以考虑加上这个功能呢。这样就可以把很久不更新的白纸插件淘汰力~

**Comment by Oishiimono** [comment]
不知道为啥，用了没反应> 不是可以吗？

**Comment by lgyseven** [comment]
> 不知道为啥，用了没反应> 不是可以吗？

优先级改一下，在Miao-Yunzai/plugins/system/add.js

**Comment by Oishiimono** [comment]
> > 不知道为啥，用了没反应> 不是可以吗？
> 
> 优先级改一下，在Miao-Yunzai/plugins/system/add.js

找到原因了，把思知AI.js的权重从默认的5000降到50000，“#添加”指令就能正常运作啦
