### ISSUE TITLE
查询充值记录失败

### ISSUE THREAD

**Issue by xueqi5201314** [yoimiya-kokomi/Miao-Yunzai#65]
无法导入链接，用链接，cookie，甚至stoken都获取不到
![THGQ@8 QZ`J}3UI$B%{(S5H_tmb](https://user-images.githubusercontent.com/108047693/232482922-1a7216f5-3dc4-47bc-a2f5-921df12c2777.jpg)

**Comment by FujishiroOtone** [comment]
同样的错误，试过单发链接也不行
