### ISSUE TITLE
Possibility to use chromium in seperated Container?

### ISSUE THREAD

**Issue by sgqy** [yoimiya-kokomi/Miao-Yunzai#72]
Just like [this](https://github.com/DIYgod/RSSHub/blob/8699b4c9d32f29ad9942f1de202531bb5fe49f9f/docker-compose.yml#L16) and [this](https://github.com/DIYgod/RSSHub/blob/8699b4c9d32f29ad9942f1de202531bb5fe49f9f/lib/utils/puppeteer.js#L60). The Image comes from [here](https://github.com/browserless/chrome).

**Comment by xiaofeiTM233** [comment]
Maybe that's what you want
![image](https://user-images.githubusercontent.com/55832499/233486695-8447906f-e95f-46ae-89e9-7e66a4ac8b6d.png)
./renderers/puppeteer/config_default.yaml
or ./renderers/puppeteer/lib/puppeteer.js

**Comment by sgqy** [comment]
Closed by #95
