### ISSUE TITLE
[Question] Dockerfile 里面的 ffmpeg 有什么作用吗？看了下代码好像没有地方用到？求大佬指点一下

### ISSUE THREAD

**Issue by xiezht** [yoimiya-kokomi/Miao-Yunzai#83]
https://github.com/yoimiya-kokomi/Miao-Yunzai/blob/23b194c6a79cf24cd3202f4770ee21b8e77266c4/docker/Dockerfile#L11

**Comment by ikuaki1009** [comment]
Yunzai-Bot 使用了 icqq，ffmpeg 用来把不是 amr 格式的音频文件转换为 amr 格式并发送出去。
